FROM python:3.7-buster

RUN apt-get update && apt-get upgrade &&apt-get install apache2 redis-server -y --no-install-recommends

WORKDIR /usr/src/app

RUN pip install --upgrade pip
COPY . .
RUN pip install -r requirements.txt
RUN python manage.py collectstatic --noinput


EXPOSE 8000
STOPSIGNAL SIGTERM
CMD ["/usr/src/app/start1.sh"]
