# Generated by Django 2.2.5 on 2020-11-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(max_length=100)),
                ('response_id', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
    ]
