# Generated by Django 2.2.5 on 2020-11-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_exportdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='managers',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='members',
            field=models.CharField(max_length=100),
        ),
    ]
